config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # express the 7 routes shown before with just one line
  resources :tasks
  # GET the restaurant creation form = 1 request
  # get "tasks/new", to: "tasks#new"
  # # POST the parameters to create a new restaurant = 1 request
  # post "tasks", to: "tasks#create"
  # # UPDATE - GET
  # get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  # # UPDATE - PATCH
  # patch "tasks/:id", to: "tasks#update"
  # # DELETE -
  # delete "tasks/:id", to: "tasks#destroy"
  # get "tasks", to: "tasks#index"
  # get "tasks/:id", to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class = "container">
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.check_box :completed %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class = "container">
  <h1>Edit task 🖊</h1>
  <%= render "form", task: @task %>
</div>

app/views/tasks/index.html.erb
<div class = "container">
  <h1>My Tasks 📝</h1>
  <ul>
    <% @tasks.each do |task| %>
      <li><%=link_to task.title, task_path(task.id) %></li>
    <% end %>
  </ul>
  <p><%=link_to "Create a new task", task_path(:new) %></p>
</div>

app/views/tasks/new.html.erb
<div class = "container">
  <h1>Create new task ✍🏽</h1>
  <%= render "form", task: @task %>

  <p><%=link_to "Back to all tasks!", tasks_path %></p>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2><%= @task.title %></h2>
  <p><%= @task.details %></p>
  <p><%= @task.completed %></p>

  <p><%=link_to "Do you want to edit this task? ✍🏽", edit_task_path %></p>
  <p><%=link_to "Back to all tasks! 🔙", tasks_path %></p>
  <%= link_to "Delete task 🗑",
              task_path(@task),
              method: :delete,
              data: { confirm: "Are you sure you want to delete this?" } %>
</div>